spring:
  datasource:
    url: jdbc:mysql://localhost/saha
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  session:
    jdbc:
      initialize-schema: always

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100GB
      max-request-size: 107GB

server:
  port: 8099

